"""initial schema phase 2a

Revision ID: 0d3d40690d49
Revises:
Create Date: 2026-07-22 00:06:11.662046

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0d3d40690d49'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name'))
    )
    op.create_table('meetings',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meetings')),
    sa.UniqueConstraint('name', name=op.f('uq_meetings_name'))
    )
    op.create_table('responsible_parties',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_responsible_parties')),
    sa.UniqueConstraint('name', name=op.f('uq_responsible_parties_name'))
    )
    op.create_table('users',
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('ADMIN', 'EDITOR', 'VIEWER')", name=op.f('ck_users_role_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_app_settings_updated_by_users')),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_app_settings'))
    )
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('before_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('after_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=45).with_variant(postgresql.INET(), 'postgresql'), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)

    op.create_table('meeting_occurrences',
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('meeting_date', sa.Date(), nullable=False),
    sa.Column('meeting_number', sa.String(length=50), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('agenda', sa.Text(), nullable=True),
    sa.Column('minutes_link', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_meeting_occurrences_created_by_users')),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_meeting_occurrences_meeting_id_meetings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting_occurrences')),
    sa.UniqueConstraint('meeting_id', 'meeting_date', 'meeting_number', name='occurrence_identity')
    )
    with op.batch_alter_table('meeting_occurrences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_occurrences_meeting_id'), ['meeting_id'], unique=False)

    op.create_table('issues',
    sa.Column('issue_code', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('responsible_party_id', sa.Uuid(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('raised_date', sa.Date(), nullable=False),
    sa.Column('raised_in_meeting_occurrence_id', sa.Uuid(), nullable=True),
    sa.Column('pic_name', sa.String(length=150), nullable=True),
    sa.Column('pic_user_id', sa.Uuid(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('last_update_summary', sa.Text(), nullable=True),
    sa.Column('last_update_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_date', sa.Date(), nullable=True),
    sa.Column('closure_note', sa.Text(), nullable=True),
    sa.Column('reopened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')", name=op.f('ck_issues_priority_valid')),
    sa.CheckConstraint("status IN ('OPEN', 'IN_PROGRESS', 'PENDING', 'CLOSED', 'REOPENED')", name=op.f('ck_issues_status_valid')),
    sa.CheckConstraint('due_date IS NULL OR due_date >= raised_date', name=op.f('ck_issues_due_after_raised')),
    sa.ForeignKeyConstraint(['archived_by'], ['users.id'], name=op.f('fk_issues_archived_by_users')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_issues_category_id_categories')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_issues_created_by_users')),
    sa.ForeignKeyConstraint(['pic_user_id'], ['users.id'], name=op.f('fk_issues_pic_user_id_users')),
    sa.ForeignKeyConstraint(['raised_in_meeting_occurrence_id'], ['meeting_occurrences.id'], name=op.f('fk_issues_raised_in_meeting_occurrence_id_meeting_occurrences')),
    sa.ForeignKeyConstraint(['responsible_party_id'], ['responsible_parties.id'], name=op.f('fk_issues_responsible_party_id_responsible_parties')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_issues_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issues')),
    sa.UniqueConstraint('issue_code', name=op.f('uq_issues_issue_code'))
    )
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issues_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_last_update_at'), ['last_update_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_pic_user_id'), ['pic_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_responsible_party_id'), ['responsible_party_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_status'), ['status'], unique=False)

    op.create_table('issue_updates',
    sa.Column('issue_id', sa.Uuid(), nullable=False),
    sa.Column('update_date', sa.Date(), nullable=False),
    sa.Column('meeting_occurrence_id', sa.Uuid(), nullable=True),
    sa.Column('update_note', sa.Text(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('action_owner', sa.String(length=150), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('status_before', sa.String(length=20), nullable=True),
    sa.Column('status_after', sa.String(length=20), nullable=True),
    sa.Column('due_date_before', sa.Date(), nullable=True),
    sa.Column('due_date_after', sa.Date(), nullable=True),
    sa.Column('pic_before', sa.String(length=150), nullable=True),
    sa.Column('pic_after', sa.String(length=150), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_by', sa.Uuid(), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('progress_percentage IS NULL OR (progress_percentage >= 0 AND progress_percentage <= 100)', name=op.f('ck_issue_updates_progress_range')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_issue_updates_created_by_users')),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], name=op.f('fk_issue_updates_issue_id_issues')),
    sa.ForeignKeyConstraint(['meeting_occurrence_id'], ['meeting_occurrences.id'], name=op.f('fk_issue_updates_meeting_occurrence_id_meeting_occurrences')),
    sa.ForeignKeyConstraint(['voided_by'], ['users.id'], name=op.f('fk_issue_updates_voided_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issue_updates'))
    )
    with op.batch_alter_table('issue_updates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issue_updates_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_issue_updates_issue_id'), ['issue_id'], unique=False)

    op.create_table('attachments',
    sa.Column('issue_id', sa.Uuid(), nullable=False),
    sa.Column('issue_update_id', sa.Uuid(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=150), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('size_bytes >= 0', name=op.f('ck_attachments_size_non_negative')),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], name=op.f('fk_attachments_issue_id_issues')),
    sa.ForeignKeyConstraint(['issue_update_id'], ['issue_updates.id'], name=op.f('fk_attachments_issue_update_id_issue_updates')),
    sa.ForeignKeyConstraint(['removed_by'], ['users.id'], name=op.f('fk_attachments_removed_by_users')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_attachments_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments')),
    sa.UniqueConstraint('stored_filename', name=op.f('uq_attachments_stored_filename'))
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_issue_id'), ['issue_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_issue_id'))

    op.drop_table('attachments')
    with op.batch_alter_table('issue_updates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issue_updates_issue_id'))
        batch_op.drop_index(batch_op.f('ix_issue_updates_created_at'))

    op.drop_table('issue_updates')
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issues_status'))
        batch_op.drop_index(batch_op.f('ix_issues_responsible_party_id'))
        batch_op.drop_index(batch_op.f('ix_issues_pic_user_id'))
        batch_op.drop_index(batch_op.f('ix_issues_last_update_at'))
        batch_op.drop_index(batch_op.f('ix_issues_due_date'))
        batch_op.drop_index(batch_op.f('ix_issues_category_id'))

    op.drop_table('issues')
    with op.batch_alter_table('meeting_occurrences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_occurrences_meeting_id'))

    op.drop_table('meeting_occurrences')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    op.drop_table('app_settings')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('responsible_parties')
    op.drop_table('meetings')
    op.drop_table('categories')
    # ### end Alembic commands ###
