"""add issue counter and phase 2b support

Revision ID: bbba43c5c105
Revises: 0d3d40690d49
Create Date: 2026-07-22 19:54:48.908490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbba43c5c105'
down_revision: Union[str, None] = '0d3d40690d49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_counters',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('year', name=op.f('pk_issue_counters'))
    )
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.create_index('ix_issues_archived_at_status', ['archived_at', 'status'], unique=False)
        batch_op.create_index('ix_issues_category_id_status', ['category_id', 'status'], unique=False)
        batch_op.create_index('ix_issues_responsible_party_id_status', ['responsible_party_id', 'status'], unique=False)
        batch_op.create_index('ix_issues_status_due_date', ['status', 'due_date'], unique=False)
        batch_op.create_index('ix_issues_status_last_update_at', ['status', 'last_update_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_index('ix_issues_status_last_update_at')
        batch_op.drop_index('ix_issues_status_due_date')
        batch_op.drop_index('ix_issues_responsible_party_id_status')
        batch_op.drop_index('ix_issues_category_id_status')
        batch_op.drop_index('ix_issues_archived_at_status')

    op.drop_table('issue_counters')
    # ### end Alembic commands ###
