# Concept by MrHan (08974747477)
from __future__ import annotations

import collections
import re

from tests.contract.conftest import iter_operations

# Readable snake_case, domain-prefixed.
_ID_RE = re.compile(r"^[a-z][a-z0-9_]+$")

# Accepted operationId prefixes (one per domain).
_PREFIXES = (
    "health_",
    "meta_",
    "auth_",
    "users_",
    "categories_",
    "responsible_parties_",
    "meetings_",
    "meeting_occurrences_",
    "issues_",
    "issue_updates_",
    "attachments_",
    "dashboard_",
    "settings_",
    "reports_",
)


def test_all_operations_have_ids(schema) -> None:
    missing = [
        f"{m.upper()} {p}" for p, m, op in iter_operations(schema) if not op.get("operationId")
    ]
    assert not missing, f"operations missing operationId: {missing}"


def test_operation_ids_unique(schema) -> None:
    ids = [op["operationId"] for _p, _m, op in iter_operations(schema)]
    dupes = [k for k, v in collections.Counter(ids).items() if v > 1]
    assert not dupes, f"duplicate operationIds: {dupes}"


def test_operation_ids_readable_and_prefixed(schema) -> None:
    for _p, _m, op in iter_operations(schema):
        oid = op["operationId"]
        assert _ID_RE.match(oid), f"unreadable operationId: {oid}"
        assert oid.startswith(_PREFIXES), f"operationId missing domain prefix: {oid}"


def test_no_autogenerated_body_names(schema) -> None:
    # Multipart body schemas are allowed as Body_<operationId>, but the long
    # autogenerated form (Body_<func>_api_v1_...) must not appear.
    for name in schema["components"]["schemas"]:
        if name.startswith("Body_"):
            assert "_api_" not in name, f"autogenerated body schema name: {name}"
